Quiron.LojaVirtual.Web/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Quiron.LojaVirtual.Dominio.Repositorio;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Categoria/

        private ProdutosRepositorio p;

        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            p = new ProdutosRepositorio();

            IEnumerable<string> categorias = p.todosProduto.Select(c => c.Categoria).Distinct().OrderBy(c => c);

            return PartialView(categorias);
        }
	}
}

Quiron.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Produto

<div class="well">
    <h3><strong>@Model.Nome</strong></h3>
    <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>

    @using (Html.BeginForm("Adicionar", "Carrinho"))
    {
        <div class="pull-right">
            
            @Html.Hidden("produtoId", @Model.ProdutoId)
            @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
            <input type="submit" value="Comprar" class="btn btn-success" />
            
        </div>
        
        
    }
    


    <h3><span class="lead">@Model.Descricao</span></h3>
</div>

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Loja virtual do Rodrigo</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <link href="~/Content/ErroEstilo.css" rel="stylesheet" />
    
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
   
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Loja Virtual do Rodrigo </a>
        @Html.Action("Resumo", "Carrinho")
    </div>

    <div class="row panel">
        <div id="categorias" class="col-xs-3">
                @Html.Action("Menu","Categoria")

        </div>

        <div id="categorias" class="col-xs-8">
            @RenderBody()
        </div>


    </div>

 
  
</body>
</html>