Quiron.LojaVirtual.Web/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Quiron.LojaVirtual.Dominio.Repositorio;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Categoria/

        private ProdutosRepositorio p;

        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            p = new ProdutosRepositorio();

            IEnumerable<string> categorias = p.todosProduto.Select(c => c.Categoria).Distinct().OrderBy(c => c);

            return PartialView(categorias);
        }
	}
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        //
        // GET: /Vitrine/

        private ProdutosRepositorio p,p1;

        private int ProdutoPorPagina = 3;

        public ViewResult ListaProdutos(string categoria, int pagina = 1)
        {
            p = new ProdutosRepositorio();

            if (categoria == null) categoria = "";

          //  p1 = new ProdutosRepositorio();

            var produto = p.todosProduto.Where(x => x.Categoria.Contains(categoria) )
                .OrderBy(x => x.Nome).Skip((pagina - 1) * ProdutoPorPagina).Take(ProdutoPorPagina);

            
            Paginacao pg = new Paginacao();
            pg.PaginaAtual = pagina;
            pg.ItensPorPagina = ProdutoPorPagina;
            pg.TotalDeItens = categoria == "" ? p.todosProduto.Count() : p.todosProduto.Count(x => x.Categoria.Contains(categoria));

            ProdutosViewModel model = new ProdutosViewModel();
            model.Produtos = produto;
            model.Paginacao = pg;
            model.CategoriaAtual = categoria;
            
            return View(model);
        }
	}
}

Quiron.LojaVirtual.Web/Views/Categoria/Menu.cshtml
@model System.Collections.Generic.IEnumerable<string>

    @Html.ActionLink("Todos os Produtos", "ListaProdutos", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg " } )

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Vitrine",
        action = "ListaProdutos",
        categoria = link.Trim(),
        pagina = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.CategoriaSelecionada ? " btn-primary" : "")
    })
}