Quiron.LojaVirtual.Web/Models/ProdutosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using  Quiron.LojaVirtual.Dominio.Entidades;


namespace Quiron.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {

        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }

    }
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Dominio.Entidades;

namespace Quiron.LojaVirtual.Web.Areas.Administrativo.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {

        private ProdutosRepositorio repositorio;

        //
        // GET: /Administrativo/Produto/
        public ActionResult Index()
        {
            repositorio = new ProdutosRepositorio();

            var produto = repositorio.todosProduto;

            return View(produto);
        }


        public ViewResult Alterar(int produtoId)
        {
            repositorio = new ProdutosRepositorio();

            var produto = repositorio.todosProduto.FirstOrDefault(x => x.ProdutoId == produtoId);


            return View(produto);

        }

        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            if (ModelState.IsValid)
            {
                repositorio = new ProdutosRepositorio();
                repositorio.Salvar(produto);
                TempData["mensagem"] = string.Format("{0} foi salvo com sucesso", produto.Nome);

                return RedirectToAction("index");
            }

            return View(produto);
        }

        public ViewResult NovoProduto()
        {
            return View("Alterar", new Produto());
        }

        //[HttpPost]
        //public ActionResult Excluir(int produtoId)
        //{
        //    repositorio = new ProdutosRepositorio();

        //    Produto produto = repositorio.Excluir(produtoId);

        //    if (produto != null)
        //    {
        //        TempData["mensagem"] = string.Format("{0} foi excluído com sucesso!!!", produto.Nome);

        //    }
        //    else
        //    {
        //        TempData["mensagem"] = string.Format("{0} falha na exclusão!!!", produto.Nome);

        //    }

        //    return RedirectToAction("index");


        //}



        [HttpPost]
        public JsonResult Excluir(int produtoId)
        {

            string mensagem = string.Empty;

            repositorio = new ProdutosRepositorio();

            Produto produto = repositorio.Excluir(produtoId);

            if (produto != null)
            {
                mensagem = string.Format("{0} foi excluído com sucesso!!!", produto.Nome);

            }
            else
            {
                mensagem = string.Format("{0} falha na exclusão!!!", produto.Nome);

            }

            return Json(mensagem,JsonRequestBehavior.AllowGet);


        }


    }
}

Quiron.LojaVirtual.Web/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Quiron.LojaVirtual.Dominio.Repositorio;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class ProdutosController : Controller
    {
        //
        // GET: /Produtos/

        private ProdutosRepositorio p;

        public ActionResult Index()
        {
            p = new ProdutosRepositorio();
            var produto = p.todosProduto.Take(10);

            return View(produto);
        }
	}
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Alterar.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Produto

@{
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
    ViewBag.Title = "Alteração de produtos";
}

<div class="panel-heading">

    <h2>  @Model.Nome        </h2>

</div>




@using (Html.BeginForm("Alterar","Produto"))
{
    //  @Html.EditorForModel(); gera automaticamente os campos

    <div class="panel-body">
        @Html.HiddenFor(x => x.ProdutoId)

        @foreach (var p in ViewData.ModelMetadata.Properties)
        {

            if (p.PropertyName != "ProdutoId")
            {

                if (p.PropertyName == "Descricao")
                {
                    <div class="form-group">
                        <label>@(p.DisplayName ?? p.PropertyName)</label>
                        @Html.TextArea(p.PropertyName, null, new { @class = "form-control", rows = 5 })
                    </div>
                }
                else
                {

                    <div class="form-group">
                        <label>@(p.DisplayName ?? p.PropertyName)</label>
                        @Html.TextBox(p.PropertyName, null, new { @class = "form-control" })
                    </div>
                }
                
               @Html.ValidationMessage(p.PropertyName);
               // @Html.ValidationSummary();

            }

        }


      <div class="panel-footer">
          <input type="submit" value="Salvar" class="btn btn-primary" />
          @Html.ActionLink("Cancelar e retornar", "Index", null, new { @class = "btn btn-warning" })
      </div>
        

        

    </div>
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Confirmacao.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel">Exclusão</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" />
                <p>Deseja excluir o produto <em><strong>"<span></span>"</strong></em>&nbsp;?</p>
            </div>

            <div class="modal-footer">
                <button class="btn btn-success" type="button">Confirmar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    $(function () {

        //Abrir o modal
        // pega a classe
        $(".btn-xs").click(function (e) {
            e.preventDefault();
            var id = this.id;
            var nome = this.name;
            $("#deleteModal .modal-body input[type=hidden]").val(id);
            $("#deleteModal .modal-body span").text(nome);
            $("#deleteModal").modal('show');
        });

        $("#deleteModal .modal-footer button").click(function (e) {
            e.preventDefault();
            var url = "/../Administrativo/Produto/Excluir/";
            var id = $(".modal-body input[type=hidden]").val();
            var rowNo = '#row-' + id;

            $.ajax({
                url: url,
                type: 'post',
                dataType: 'json',
                data: { produtoId: id },
                beforeSend: function () {
                    var loading = "<span><em>Excluindo</em>&nbsp;<i class='glyphicon glyphicon-refresh icon-refresh-animate'></i></span>";
                    $('#deleteModal .modal-header h4').after(loading);
                },
                success: function () {

                    $('#deleteModal').modal('hide');

                    $(rowNo).animate({ opacity: 0.0 }, 400, function () {
                        $(rowNo).remove();
                    });
                },
                complete: function (data) {
                    $("#divexcluir").empty();
                    $("#divexcluir").addClass("alert alert-success");
                    $("#divexcluir").html(data.responseText);
                }
            });
        });
    });
</script>

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Index.cshtml
@model IEnumerable<Quiron.LojaVirtual.Dominio.Entidades.Produto>

@{
    ViewBag.Title = "Administrativo - Produtos";
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

@*<div class="alert alert-success" id="mensagem"></div>*@


<div id="divexcluir"></div>




<div class="panel panel-default">

    <div class="panel-heading">
        <h3>Quiron Loja Virtual - Administrivo - Produtos</h3>
    </div>
 <div class="panel-body">

     @Html.ActionLink("Novo produto", "NovoProduto", "Produto", new { @class = "btn btn-default" })

     <table class="table table-striped table-condensed table-bordered">

            <thead>

                <tr>
                    <th class="text-right">#Id</th>
                    <th>Nome</th>
                    <th class="text-right">Preço</th>
                    <th class="text-center">Excluir</th>
                </tr>

            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr id="row-@item.ProdutoId">

                        <td class="text-right">
                            #  @item.ProdutoId
                        </td>

                        <td>
                            @Html.ActionLink(item.Nome, "Alterar", new { item.ProdutoId })
                        </td>

                        <td class="text-right">
                            @item.Preco.ToString("c")
                        </td>

                        <td class="text-center">

                            @*@using (Html.BeginForm("Excluir", "Produto"))
                            {
                                @Html.Hidden("ProdutoId", item.ProdutoId)

                                <input type="submit" class="btn btn-xs btn-danger" value="Excluir" />
                            }*@

                            <input type="submit" id="@item.ProdutoId" name="@item.Nome" class="btn btn-xs btn-danger" value="Excluir" data-toggle="tooltip" data-placement="left" title="Exclui o produto" />
                           

                        </td>

                    </tr>
                }


            </tbody>

        </table>

    </div>
</div>

@Html.Partial("Confirmacao")